### PR TITLE
refactor: remove telegram dm sessions feature switch

### PR DESCRIPTION
**Pull request by hulh122**
## Summary

Retire `_telegramDmSessions` as **fully-rolled-out**. Official and custom Telegram bots now always use agent/model/service-tier-scoped main DM sessions and independent reply chains; a per-user switch override can no longer select the single-session behavior.

- Remove the enum and registry entries, ingress switch lookup, `scopedDmSessions` argument, and disabled-state `dm` branch. All incoming DMs preserve their thread settings and bind reply-message anchors directly.
- Keep model switching and switching back, pinned reply-chain settings, native reply delivery, multi-chunk answer anchors, and `/new_session` behavior. Group routing remains the same.
- Keep shared integration session helpers and the existing legacy `dm` reset/callback readers: persisted routes and callbacks remain supported. No schema, migration, frontend, or Runner protocol changes are needed. Existing core filtering excludes overrides for unregistered switches.

## Rollout and history

- Terminal-state evidence: [#34379](https://github.com/vm0-ai/okou/pull/34379), merged on September 15, enables the switch globally and records the completed compatible-reader deployment. Activation commit: `a480755db4d3e97152191ceb51c834afa5dc4a30`.
- Introduction: [#34327](https://github.com/vm0-ai/okou/pull/34327), `2779ebf6aea5a8276f3ff183b4e4574c5579261a`. Its parent routed every DM to `dm` and reconciled the selected model into that thread. Comparing the introduction patch and parent with current code confirms this PR retains the enabled path and deletes only the disabled ingress behavior.
- Preserve the later split between reply-anchor and pinned-reply scenarios from `cafedd90b0ccafb4fdbba12d56a0dc034749b693` ([#34447](https://github.com/vm0-ai/okou/pull/34447)).

## Tests and residual search

- Remove the two disabled-state model cases, their unsplit-DM assertions, and switch override setup/imports. The six official/custom bot cases now exercise the permanent behavior directly. No tests are added.
- Exact/key-variant and secondary searches cover `_telegramDmSessions`, `TelegramDmSessions`, `telegram-dm-sessions`, `telegram_dm_sessions`, `scopedDmSessions`, `isScopedDm`, `unsplit DM`, and `scoped sessions enabled`: no tracked-code matches remain.
- Inspect the remaining `rootMessageIdForAgentMessage`, `integrationDmSessionKey`, `INTEGRATION_DM_SESSION_PREFIX`, `isIntegrationDmSessionKey`, `preserveThreadSettings`, `bindTelegramReplyMessageRoute`, `persistTelegramReplyChainRoute`, and legacy `dm` matches. They implement retained product behavior, shared integration logic, or persisted-context compatibility.

## Validation

- Passed: Core feature-switch tests (35), Core type checks, Core lint and both changed API files' lint (Oxlint, type-aware Oxlint, ESLint), changed-file Prettier, and `git diff --check`.
- API dependency declarations and project boundary checks passed, including six boundary-tooling tests. The aggregate `TSC_CHECKERS=1 pnpm --filter api check-types` did not complete within a 240-second execution bound (exit 124); its remaining compiler process was explicitly stopped. Full API types remain unverified.
- Local Telegram API regression is **incomplete**. Both single-worker attempts (default forks and threads) produced only the Vitest `RUN` banner and no completed test report after about five minutes. Processes repeatedly entered I/O wait; available memory was about 200 MB with no swap, and a local PostgreSQL status query also stalled. Both attempts were stopped manually, with the threaded process ultimately requiring SIGKILL; exit 137 is from that termination, not a test assertion or a confirmed OOM kill. The dedicated local database migrated successfully and was stopped afterward.
- Scoped Knip (`--workspace apps/api --workspace packages/core`) could not load the unrelated `apps/app-worker/eslint.config.mjs`: `Cannot find module '@okouai/eslint-config/base'` (exit 2). This checkout installed only API/Core dependency workspaces; Knip still loads other workspace configuration. Full Knip remains delegated to CI.
- Draft pending Telegram API regression, full API type checking, Knip, and the PR pipeline's full repository checks. No local dev server or full-repository Vitest run was used.

### CODE REVIEW

**Comment by hulh122** [comment]
LGTM


PR_AUTO_REVIEW_COMMIT: 0f6f89f9ba1e5647848351b6dd7cf2ec0feb9493
PR_AUTO_REVIEW_VERDICT: LGTM

### Summary

Retires the fully enabled `_telegramDmSessions` switch and makes its existing agent/model/service-tier-scoped DM sessions and independent reply chains permanent. The four-file diff removes the disabled ingress path and its two test cases, preserves all six enabled-behavior scenarios, and retains the fixture isolation introduced by #34639 when resolving the conflict with `main`.

Reviewed the complete diff, all four changed files, the official/custom webhook callers, session-key helper, and Telegram route persistence consumers. Practice documents were read from `main` at `1d320051407b42f6c97176499949d92951f582fd`; the authoritative `REVIEW.md` was also fetched directly from GitHub `main` before posting.

### Review Criteria

| Source | Core item | Result | Evidence |
| --- | --- | --- | --- |
| `REVIEW.md`; `docs/docs.md` | Trace the complete changed behavior and select practices for the affected surfaces | Pass | Traced official/custom private and group webhook entry points through `handleTelegramAgentMessage$`, persistence, route reuse, and reply callbacks; the PR changes API routing and tests plus the Core switch registry. |
| `REVIEW.md` | Preserve authorization, ownership, idempotency, ordering, and cancellation | Pass | Webhook-secret validation and linked-user resolution are unchanged. Owner-scoped route keys, deterministic chat-event IDs, transactional inserts, and cancellation checks remain intact. |
| `docs/bad-smell.md` | Remove obsolete branches without adding speculative abstractions or silent defaults | Pass | `rootMessageIdForAgentMessage` retains the previous enabled branch directly; `persistTelegramChatMessage$` uses `isDM` because its only producer can no longer emit the disabled `dm` key. Shared helpers still have live consumers. |
| `docs/fallback.md` | Require evidence for retired paths and remove their tests together | Pass | #34379 (`a480755db4d3e97152191ceb51c834afa5dc4a30`) globally enabled the switch after compatible readers were deployed. The introduction and its parent were compared with current code; the disabled branch, enum, registry, overrides, and disabled tests are removed together. |
| `docs/fallback.md`; `REVIEW.md` | Declare and bound every newly introduced fallback; avoid tombstone tests | Pass | No fallback or tombstone test is introduced. Existing persisted `dm` reset/callback readers remain unchanged; this cleanup does not claim old persisted contexts are absent. |
| `.claude/skills/feature-switch/SKILL.md` | Keep switch registration and consumers consistent; cleanup needs no replacement gate | Pass | Enum and registry entries are removed together. Tracked-code key/variant and secondary searches find no retired switch consumer. Existing Core filtering ignores unregistered overrides. |
| `docs/testing.md`; `REVIEW.md` | Preserve meaningful behavior coverage for the retained path | Pass | Six official/custom cases still assert model switching and switching back, multi-chunk reply anchors, earlier-message continuation, and pinned reply-chain models. Group, reset, web continuation, and idempotency scenarios remain. |
| `docs/testing/api-testing.md` | Exercise real routes and preserve per-test fixture ownership | Pass | The affected scenarios use production onboarding/link/webhook/runner APIs and external Telegram mocks. `prepareTelegramDm` stays in `beforeEach`, preserving #34639's isolation; no shared fixture or timing workaround was added. |
| `docs/testing/testing-external-behavior.md` | Construct and assert the changed scenarios through external interfaces | Pass | DM scenarios verify runner claim/session results and Telegram reply delivery. The diff introduces no internal service/DB mutation helper or log assertion. |
| `.claude/skills/ccstate/SKILL.md`; `.claude/skills/ccstate/references/commands.md` | Keep commands scoped and await finite subcommands | Pass | Commands remain module-scoped; removal of the feature lookup only removes an unused `get` accessor. Existing subcommand calls remain awaited. |
| `.claude/skills/ccstate/references/lifecycle.md` | Preserve async owners and cancellation propagation | Pass | Existing `AbortSignal` arguments and checks after model resolution, persistence, and downstream calls are retained; no detached work or new controller is introduced. |
| `REVIEW.md` | Assess persisted shapes and cross-version contracts | Pass | No schema, JSONB shape, endpoint, callback payload, or Runner protocol changes. Existing session-key format and historic callback readers remain supported. |
| `CLAUDE.md`; `.claude/skills/commit/SKILL.md` | Scope verification to affected consumers and distinguish incomplete checks | Pass | Scoped formatting/static checks and 35 Core tests passed. Local API regression remains incomplete; current-head required CI is still the merge gate, as detailed below. |

### Findings

No blocking findings.

### Testing

- After resolving the conflict: changed-file Prettier, ordinary Oxlint, type-aware Oxlint, ESLint, and `git diff --check` passed; Core feature-switch tests passed **35/35**. The dedicated local database migrated successfully.
- The scoped `integrations-telegram-post.test.ts` attempt produced a `RUN` banner but no completed report before the local execution ended. It is **not** counted as a pass. Earlier bounded attempts and local API type/Knip limitations are recorded in the PR description.
- On the preceding head `83bc38ac3f29c2a06b21f4902daee310cd03e12e`, GitHub passed all eight API test shards, API/App/Core type/lint gates, and Knip. The two failures were in Playwright feature tests (artifact theme attribute and avatar-dialog interaction); those logs have been inspected and are not evidence of a Telegram routing defect.
- CI for this reviewed head is pending. Old-head results do not substitute for the new head's required checks. No full local Vitest suite or local development server was run.
