### PR TITLE
fix(e2e): drain page route handlers before fixture teardown

### LINKED ISSUE #32396: fix(e2e): drain page route handlers before fixture teardown
## Problem and evidence

The `cli-e2e-02-playwright (features)` job in [run 34134415761](https://github.com/vm0-ai/vm0/actions/runs/34134415761/job/101783810284?pr=32385) failed in `dark theme > focused composer does not cast a dark veil`:

```text
route.fetch: Target page, context or browser has been closed
GET /api/user-preferences
e2e/playwright/tests/chat.spec.ts:29
```

The job reports one failed test and ten passed tests; it reports a route callback error, not a failed theme/focus/shadow assertion. The test added by #32351 (`a7ff47cfdb09d8370ed94ca0ffb788a6ea963dc5`) starts an asynchronous real upstream fetch, rewrites only the theme preference, and does not drain route handlers before the page fixture is destroyed. Dark mode can already be applied from the emulated system preference while the server preference read remains in flight. PR #32385 changes only runner doctor, the host collector, collector regressions and deployment documentation, not this test or its frontend/API dependencies.

The shared `e2e/playwright/fixtures.ts` currently owns preview cookies but no page-route teardown. The adjacent pinned-agent loading test also registers an asynchronous page route; it releases its gate in `finally` but does not await the handler. The standalone connector-card regression already drains routes with `behavior: "wait"` before closing its page.

## Requirements

- The fixture-managed page must remain alive until already-running page route handlers finish, on both successful and failed tests.
- Preserve real network and callback failures. Do not use `ignoreErrors`, blanket catches, retries, sleeps, longer timeouts or test skips as the fix.
- Preserve the existing dark-theme, focus, shadow and pinned-agent geometry assertions, real preview requests and shared-account isolation.
- Add deterministic browser/HTTP integration coverage for the fixture lifecycle, including in-flight requests and error visibility.
- No production UI, API, runner or deployment behavior changes.

## Acceptance criteria

- A delayed intercepted request that outlives a test body completes before its page/context closes.
- The same cleanup runs after an assertion failure; the original failure remains observable.
- A failing route callback is still reported as a failed test.
- E2E type checking, formatting and fixture integration tests pass; the deployed features lane validates the unchanged product assertions.

This is a standalone, single-PR test-infrastructure fix. It does not implement or close #32084 or alter PR #32385.

### PR DESCRIPTION
**Pull request by seven332**
## Summary

Closes #32396.

- Drain registered page route callbacks before the shared Playwright page fixture returns to the built-in page/context owner, including after assertion failures.
- Preserve real callback failures using `behavior: "wait"`; do not swallow errors, retry, extend deadlines or change product assertions.
- Add real Chromium/loopback HTTP integration tests through the Playwright CLI and the actual shared fixture. The tests cover successful teardown, original assertion failures and route callback failures. Document gate-release and manual-page ownership.

## Root cause

[The features job on PR #32385](https://github.com/vm0-ai/vm0/actions/runs/34134415761/job/101783810284?pr=32385) failed at `chat.spec.ts:29` with `route.fetch: Target page, context or browser has been closed` during GET user-preferences. The dark composer test introduced by #32351 can finish its theme/focus/shadow assertions using the emulated dark system preference while the real preference request is still in flight. The page fixture previously had no route-completion owner. #32385 itself does not change this browser path.

The regression harness holds the upstream request until fixture teardown begins and checks completion before context teardown/page closure. On the unmodified fixture, both successful-body and failing-body cases fail with `ROUTE_NOT_DRAINED` and a disposed response. The fixed fixture completes callbacks first. Intentional child-process failures are asserted by passing parent integration tests, not skipped or expected-failure annotations.

## Scope and risks

The runtime fix is eight lines in the shared E2E fixture. The existing chat/agent spec files, UI, API, runner, auth state, database, deployments and CI workflow are unchanged. No cross-version runtime contract is affected. Issue #32084 and the changes in PR #32385 are outside this PR's scope.

The fixture stays lazy and preserves its original context/browser options. Teardown now waits for registered running handlers; tests must release their own gates first. A genuinely stalled handler remains a visible failure under existing request/teardown timeouts. Manually created pages and context routes retain their existing owners.

## Validation

- Scoped Prettier check: passed.
- `cd e2e && pnpm check-types`: passed.
- `cd e2e && pnpm test`: 39 passed, 0 failed/skipped.
- `cd e2e && CI=1 pnpm test`: 39 passed, 0 failed/skipped on the final worktree.
- `CI=1 pnpm exec tsx --test playwright/lib/fixtures.test.ts`, three consecutive runs: 9/9 passed.
- `git diff --check`: passed.
- Required post-pull local database migration: passed (no schema changes).

E2E has no ESLint/Knip workspace configuration; unrelated Turbo, Rust and Python suites were not selected. Deployed features assertions are validated by this PR's CI, not claimed as locally executed. No merge performed.

### CODE REVIEW

**Comment by seven332** [comment]
## Code Review: PR #32399

**Reviewed head:** `b6f7f561b60212bece29266ffac40b5e519d5f9c`

### Summary

The shared lazy page fixture now owns completion of registered route callbacks before context teardown. Existing browser options, product assertions, real requests and error visibility are preserved. The change matches the challenged plan for #32396; no production or deployment contract changes.

### Findings

No findings after six focused self-review passes and current-head code-quality review. Test-controlled gates still need release before teardown; genuinely stalled callbacks remain visible under existing deadlines.

### Testing

Scoped Prettier, E2E TypeScript and diff checks passed. The full fixture integration suite passed 39/39, including a CI-mode run; the focused three-case suite passed three consecutive repeats (9/9). The real Playwright/Chromium/HTTP harness detects the pre-fix ownership gap and preserves intentional body/callback failures. No skipped tests, sleeps, retries or error suppression were introduced.

Deployed features assertions were not run locally; current-head CI is a separate readiness gate. Unrelated Turbo/Rust/Python suites were not selected.

### Verdict

LGTM. No merge performed.
