### PR TITLE
test(sandbox): declare tokio features for standalone tests

### LINKED ISSUE #33482: test(sandbox): declare tokio features required by standalone tests
## Problem

The documented package-scoped Rust test workflow fails when `sandbox` is selected alone. Its existing `guest_agent_process_handle_transfers_process_and_control` test uses `#[tokio::test]`, but the crate only enables Tokio's `io-util` and `sync` features. It has no development dependency enabling `macros` and `rt`. Selecting consumers such as Firecracker or Runner hides the missing test dependency through feature unification.

Observed while validating #33463, with the relevant manifest and test unchanged from main commit `a83ffce3cde42c90eff96bab4d533862b4713c4f`. This is a standalone test configuration issue, not a prerequisite for SSH sessions.

## Reproduction

Environment: Linux, rustc/cargo 1.98.1, locked workspace dependencies.

```sh
CARGO_BUILD_JOBS=1 cargo test --locked --manifest-path crates/Cargo.toml --profile local -p sandbox
```

The command fails to compile the library tests:

```text
error[E0433]: cannot find `test` in `tokio`
    --> sandbox/src/types.rs:1593:14
1593 |     #[tokio::test]
```

Explicitly providing the missing test features succeeds without source changes (33 tests pass):

```sh
CARGO_BUILD_JOBS=1 cargo test --locked --manifest-path crates/Cargo.toml --profile local -p sandbox --features tokio/macros,tokio/rt --lib
```

## Expected behavior and acceptance criteria

- `cargo test --locked --manifest-path crates/Cargo.toml --profile local -p sandbox` compiles and passes without selecting unrelated crates or supplying dependency feature flags.
- Declare the features required by the crate's own tests in its development dependencies; preserve production dependency features.
- Retain the existing behavior test and verify the package-scoped suite with locked dependencies.

Relevant files: `crates/sandbox/Cargo.toml`, `crates/sandbox/src/types.rs`, `docs/testing/rust-testing.md`.

### PR DESCRIPTION
**Pull request by seven332**
## Summary

- Declare workspace-inherited Tokio `macros` and `rt` as `sandbox` development features so its existing async test compiles when the package is selected alone.
- Keep production dependency features, test behavior, CI configuration, and `Cargo.lock` unchanged.

Closes #33482

## Validation

On main `54efc258e9`, the exact package-scoped command failed with E0433 (`tokio::test` missing at `sandbox/src/types.rs:1593`). After this change, on Linux with Rust/Cargo 1.98.0, the same command passes all 43 tests (33 unit, 9 integration, 1 trybuild; doctests also pass with 0 cases).

Passed sequentially, using `CARGO_BUILD_JOBS=1` for compilation:

- `cargo test --locked --manifest-path crates/Cargo.toml --profile local -p sandbox`
- `cargo check --locked --manifest-path crates/Cargo.toml --profile local -p sandbox --lib`
- `cargo fmt --manifest-path crates/Cargo.toml -p sandbox -- --check`
- `cargo clippy --locked --manifest-path crates/Cargo.toml --profile local -p sandbox --all-targets --all-features -- -D warnings`
- `cargo doc --locked --manifest-path crates/Cargo.toml --profile local -p sandbox --no-deps`
- `git diff --check`

The normal/build dependency tree from `cargo tree --locked --manifest-path crates/Cargo.toml -p sandbox -e normal,build -f '{p} features=[{f}]'` is identical before and after. Tokio `rt` was already provided transitively; this change explicitly owns the async test's requirements without enabling test macros in normal builds. No extra package selection or dependency feature flags were used for the passing test command.

Workspace-wide/deployed CI is not represented by these local results; required checks must pass before merge. No runtime behavior or performance change is intended.

### CODE REVIEW

**Review by seven332 — COMMENTED** [review]
LGTM

## Summary

Reviewed `07f9a2cec12af61ab1b71b9bc0bbf7a91b3e19c8` against practices from main `3e4a5d0c1957d0673d3774dd585630bcde0f2833`. The one-line development dependency declares the existing async test's Tokio requirements without changing production dependencies, test behavior, or lockfile.

## Findings

No findings. All six focused self-review passes completed cleanly on the unchanged submitted head; no fixes or follow-up issues were needed.

## Testing

Baseline standalone test compilation failed with E0433. After the fix, the exact locked package-scoped command passed 43 tests (33 unit, 9 integration, 1 trybuild; doctests: 0). Normal library check, fmt, all-target/all-feature clippy, docs, and whitespace checks passed. The normal/build dependency graph is identical before/after. No new fallback is introduced.

Workspace-wide/deployed CI was not run locally and must pass independently. This review does not authorize merging.

**Comment by seven332** [comment]
## Code Review: PR #33488

**Reviewed head:** `07f9a2cec12af61ab1b71b9bc0bbf7a91b3e19c8`

### Summary

LGTM. Development-only Tokio feature ownership fixes isolated sandbox test compilation; production dependencies, test behavior, and lockfile are unchanged. The full six-pass self-review loop completed without findings or head changes.

### Findings

No findings or follow-up issues.

### Testing

Reproduced baseline E0433. The identical locked package command now passes 43 tests, including integration and trybuild coverage. Library check, fmt, all-target clippy, docs, and whitespace checks passed; normal/build dependency graph is unchanged. Workspace-wide/deployed CI remains independently required.

### Verdict

LGTM for this exact head; not a CI-success or merge-approval record. A commit-bound review records the same conclusion per REVIEW.md.
