### PR TITLE
feat: deliver official automation results by email

### LINKED ISSUE #29700: feat: deliver official automation results by email
Parent: #28905

Depends on: #29626 (accepted on `main` as `a22b7d6bca5d3e67b82e31e9e2fcd1513abe5a7a` via #29660)

## Objective

Add one Official-only per-Automation result-email option and deliver at most one generic branded result email for every eligible successful Automation Run through the existing durable email outbox.

This is EPIC #28905 P5. It is generic Official Workflow infrastructure. It must not reuse or modify the bespoke Morning Brief callback, delivery state, renderer, schedule, or unsubscribe path.

## Current main facts

- Official Blueprint runtime settings are currently a strict empty object at `turbo/packages/api-contracts/src/contracts/official-workflow-catalog.ts:170`.
- Every Automation Run records `workflowAutomationId`, and schedule/event/explicit launch sources converge through `workflow-automation-launch.service.ts`; callback construction preserves `publicBrand` at `turbo/apps/api/src/signals/services/workflow-automation-launch.service.ts:163`.
- Terminal callbacks are dispatched only after terminal Run state is durable, and callback errors are logged without changing Run success at `turbo/apps/api/src/signals/services/agent-webhook-complete.service.ts:506`.
- Final output is available through `getRunOutputText` in `turbo/apps/api/src/signals/services/run-output.service.ts:6`.
- `email_outbox` already carries envelope, `publicBrand`, strict template payload, retry state, and drain indexes, but has no durable source identity or uniqueness constraint (`turbo/packages/db/src/schema/email-outbox.ts:27`).
- Existing templates include a bespoke `morning-brief` template. This issue must introduce a generic Official Automation result template rather than extend or call that renderer (`turbo/apps/api/src/signals/services/email-common.service.ts:65`).

### Official-only option

- Extend strict Official Blueprint runtime settings with exactly one boolean for result email (use one stable catalog key and a clearly Official-only persisted Automation projection field).
- Materialize the option during Official install/reconfiguration/catalog projection; ordinary Automations default to disabled/null and cannot set or mutate it through ordinary Workflow/Automation contracts.
- Treat the option as Definition-controlled and read-only. It is not a generic delivery-target object.
- Ensure all existing generic copy/clone/remix paths omit the Official-only capability. P4 will add Official Copy/Remix UX, but the storage/API invariant must already prevent transfer.

### Eligibility and callback flow

- Eligible: a successfully completed Run attributed to an Installed Official Automation whose result-email option was enabled for that launch.
- Cover schedule, event, once, and explicit Automation `Run now` through their shared launch/completion boundary.
- Exclude failed/cancelled Runs, direct non-Automation Workflow Runs, ordinary Automation Runs, and disabled-option Runs.
- Preserve the launch-time `publicBrand` through unattended completion, sender, product CTA links, and unsubscribe UI. Do not infer a potentially different brand at callback retry time.
- Use the Run owner/account email under existing organization/user authorization semantics.

### Durable idempotent outbox

- Give the outbox item a durable, strict source identity unique for the eligible `(runId, workflowAutomationId)` pair (or a normalized equivalent with the same invariant).
- Enqueue atomically with `ON CONFLICT DO NOTHING` or an equivalently proven database uniqueness protocol so callback retries, duplicate terminal delivery, and concurrent workers produce at most one outbox row.
- Account-level email unsubscribe must be checked before enqueue. Existing suppression and retry behavior must still be enforced by the drain/send boundary.
- Callback or enqueue failure must be observable/retryable independently and must never change a successfully completed Agent Run to failed.

### Generic renderer and safety

- Add a generic Official Automation result template with a product CTA back to the Run/thread and the existing brand-aware manage/unsubscribe affordance.
- Render only escaped text. Never accept or interpolate raw output HTML.
- Define and test explicit bounds for subject/title, result text, and generated email size. Truncate deterministically with a visible indication and keep the CTA usable.
- Handle missing/empty materialized output safely without retry loops or bespoke content inference.
- Continue using the existing outbox drain, retry, TTL, sender, suppression, and Resend integration.

## Concurrency and migration coordination

- P2 is merged and independently accepted as `4892c7a9539f11c3a919dfd4c125d2c9532641f1` via #29809. P5 resumed in its dedicated implementation thread on 2026-08-27.
- Rebase the preserved P5 work semantically onto live `main`, preserve P2 exact Official provenance/admission and #29442 removals, then replace the earlier P2-bound proof gaps with real Official schedule, event, once, and explicit `Run now` launch coverage.
- Re-scan live main, merge queue, and all open PR migration files before generation and queueing, and generate the migration naturally from the current canonical journal. P3 #29923 is concurrent: first-merge-wins applies, so overlap or migration-number competition is inventory rather than an ordering blocker.

## Acceptance criteria

- [ ] The strict Official Blueprint catalog accepts exactly one result-email boolean and rejects unknown or malformed runtime fields.
- [ ] The option is persisted only for Official Automations, is read-only through ordinary mutation APIs, and is absent from ordinary copies/remixes/clones.
- [ ] One successful eligible schedule, event, once, or explicit `Run now` Run produces exactly one outbox row despite repeated/concurrent callback delivery.
- [ ] Failed/cancelled, direct Workflow, ordinary Automation, and disabled-option Runs produce no result-email outbox row.
- [ ] Account unsubscribe prevents enqueue; suppression and outbox retry remain effective at send time.
- [ ] Public brand, sender/link domain, CTA, manage/unsubscribe behavior, and launch ownership remain consistent through unattended completion and callback retry.
- [ ] Output is escaped and bounded; empty, oversized, and hostile-looking output cases are tested.
- [ ] Email callback/enqueue/send failure does not change the completed Run status.
- [ ] No bespoke Morning Brief table, callback, template behavior, route, schedule, or delivery state is used or changed.

## Verification and handoff

- Add focused DB-backed integration tests for all eligibility sources, idempotent concurrency/retry, unsubscribe/suppression, brand preservation, renderer escaping/bounds, ordinary mutation/copy isolation, and failure independence.
- Add/update strict JSONB contract and physical identity inventory tests for every new schema identity.
- Run formatting, diff check, affected lint/type checks, targeted tests, migration consistency/generator checks, and the full PR pipeline. Per repository policy, do not run the full local Vitest suite or start a dev server.
- Self-review the complete GitHub PR diff against this issue and #28905. Keep auto-merge disabled until an independent controller review explicitly clears the exact head; after P2 has merged and this head is rebased/revalidated, use only the protected normal merge queue, never direct merge or bypass.

## Non-goals

- P2 exact Official artifact execution or Run provenance.
- P3 Blueprint reconciliation.
- P4 product UI.
- Morning Brief Definition/rollout, bespoke Morning Brief changes, production release, or legacy cleanup.

### PR DESCRIPTION
**Pull request by lancy**
## Summary

- add one strict Official-only `resultEmail` Blueprint setting and persist its nullable per-Automation projection without exposing it to ordinary mutation or copy paths
- snapshot eligibility, Automation identity, Workflow name, and public brand into the durable Run callback for schedule, event, once, and explicit `Run now` launches
- enqueue one bounded, escaped, branded result through the existing email outbox using a permanent per-Run/per-Automation source claim that survives outbox TTL cleanup and Automation uninstall
- keep suppression-at-send, outbox retry/TTL, public branding, and Run-success independence unchanged

## Unsubscribe serialization

The callback performs its final account-preference decision inside the same transaction that creates the permanent source claim and outbox row. It first materializes `users(id)` with `ON CONFLICT DO NOTHING`, which never overwrites `email_unsubscribed = true` and makes an otherwise absent Clerk identity lockable. It then takes `SELECT ... FOR UPDATE`, re-reads `email_unsubscribed`, and creates no claim or outbox row when the locked value is true. Both the explicit unsubscribe route and complaint handler upsert `email_unsubscribed = true` on that same unique key, so missing-row inserts and existing-row updates serialize with the enqueue transaction.

Deterministic DB-backed coverage proves both linearized orderings from an initially absent `users` row: unsubscribe commits while completion is paused after its initial observation, then the final re-read skips with no source rows; and completion materializes/locks first, the real unsubscribe POST is observed in PostgreSQL's blocking chain, then completion commits exactly one source/outbox before the writer commits `true`. No timing sleep, retry, forced exit, or inflated timeout is used.

## Verification

- rebased onto canonical main `3941a9832964c22b647213509376be0fccb70683`; its two post-#29938 changes have zero P5 file and migration-journal overlap
- naturally retained `1016_short_korvac` from canonical journal tail `1015_canonical_built_in_provider_schema`; `pnpm --filter @okouai/db db:generate` reports no schema changes
- fresh PostgreSQL 18 database configured to UTC, migrated through `1016_short_korvac`
- Official production launch paths and immutable lifecycle: `official-workflows.test.ts` 16/16
- callback lifecycle, both absent-row unsubscribe interleavings, cancellation/failure exclusion, TTL/redrive, renderer bounds, and callback independence: `official-automation-result-email.test.ts` 9/9
- both new absent-row interleavings also passed independently: 1/1 and 1/1
- focused result-email migration replay/schema validator passed
- email-outbox and permanent-claim physical identities: 2/2
- full API lint passed, all API type-check partitions passed, changed-file Prettier check passed, `pnpm knip` passed, and `git diff --check` passed
- exact-head PR pipeline for `21ddde572c31fd3e592a6bd10934a2f2d207dacf` is pending

## Fallbacks

None. This PR introduces no compatibility fallback: Official catalog runtime payloads and persisted Official Automation bindings require the single P5 shape while the feature remains staff-only and non-GA.

## Scope

This does not implement P3 reconciliation, P4 UI, P7/P8, a Morning Brief Definition, bespoke Morning Brief delivery changes, legacy cleanup, or a production release.

Part of #28905.
Closes #29700.

### CODE REVIEW

**Review by lancy — COMMENTED** [review]
Changes Requested

### Summary

Exact-head review for `1a9b70fd0711a716bf19be78c9784f218abbd321` against #29700 and #28905 P5. The launch-snapshotted eligibility/brand path, Official explicit/schedule/once/webhook coverage, reconfiguration and uninstall behavior, permanent source claim, TTL/redrive handling, bounded escaped renderer, and ordinary-copy isolation are materially aligned. This head is not cleared because it adds compatibility behavior that the repository explicitly forbids for this non-GA staff-only feature, and it adds a schema-only unit test contrary to the integration-first test rules.

### Findings

#### Critical (P0) - must fix before merge

- None.

#### High Priority (P1) - should fix before merge

- `turbo/packages/api-contracts/src/contracts/official-workflow-catalog.ts:officialWorkflowAcceptedRuntimeSettingsSchema` accepts an immutable accepted Blueprint with the pre-P5 `runtime: {}` shape by defaulting `resultEmail` to `false`. `OfficialWorkflows` is still globally disabled/staff-only, and the sole deployed source catalog still contains `definitions: []`. `docs/fallback.md` section 2 explicitly says not to add old-shape tolerance, migrations, or backfills for a feature behind a non-GA switch. Remove this read fallback and require the same strict `resultEmail` boolean on accepted payloads.
- `turbo/packages/db/src/migrations/1014_zippy_legion.sql:zero_workflow_automations_default_official_result_email` plus the `UPDATE` backfill preserve pre-P5 staff rows and a draining P2 writer. That is the same prohibited non-GA compatibility path, and it leaves a function/trigger in migrated production databases that does not exist in a freshly generated schema. Remove the function, trigger, backfill, their permanent/legacy identity entries, and the compatibility-specific migration assertions; regenerate `1014` in place from the canonical schema. A transient staff-only cutover failure is expressly acceptable under `docs/fallback.md`.
- The PR body has no required `## Fallbacks` declaration. The summary's one-line compatibility claim does not name each file/symbol, surface/gate, removal condition, or follow-up. This is independently P1 under `docs/fallback.md` section 9. The requested repair is to remove the unjustified behaviors; if any compatibility behavior remains, it must be explicitly declared and bounded before a fresh review.
- `turbo/packages/api-contracts/src/contracts/official-workflow-catalog.test.ts` directly proves Zod accepts/rejects object shapes. `docs/testing.md` and `docs/testing/anti-patterns.md` explicitly exclude schema-validation tests, and the meaningful malformed-runtime behavior is already covered through the catalog sync route in `cron-official-workflow-catalog.test.ts`. Remove this schema-only unit test and keep the route-level business coverage.

### Fallbacks

- `turbo/packages/api-contracts/src/contracts/official-workflow-catalog.ts:officialWorkflowAcceptedRuntimeSettingsSchema` — protects new API reads of pre-P5 accepted `runtime: {}` payloads; surface `none — non-GA feature switch`; removal condition/follow-up absent; declared in PR summary `No — P1`; verdict `Not justified`.
- `turbo/packages/db/src/migrations/1014_zippy_legion.sql:UPDATE zero_workflow_automations` — backfills pre-P5 staff-created Official Automation rows; surface `none — non-GA feature switch`; removal condition/follow-up absent; declared in PR summary `No — P1`; verdict `Not justified`.
- `turbo/packages/db/src/migrations/1014_zippy_legion.sql:zero_workflow_automations_default_official_result_email` — protects a draining P2 API writer after the P5 migration; nominal DB/API skew, but gated by the same non-GA staff-only switch; removal condition/follow-up absent; declared in PR summary `No — P1`; verdict `Not justified`.

### Testing

- Coverage: functionally adequate for the P5 lifecycle. The exact head's canonical `test-migrate` job passes after the database-identity inventory repair, and focused coverage exercises real Official launch producers, launch-time brand, reconfiguration, uninstall, concurrent callback delivery, permanent claim retention, TTL cleanup/redrive, unsubscribe/suppression, renderer bounds/escaping, and ordinary behavior.
- Conventions: one P1 violation remains: the schema-only Zod test above. The route-level and DB-backed integration tests otherwise use the repository's focused boundaries.
- Any head change invalidates this review. Keep auto-merge and queue entry disabled until a fresh exact-head controller clearance.

**Review by lancy — COMMENTED** [review]
LGTM

### Summary

Exact-head controller review clears `9ff8a81105390a87626d15cba87c5d863def1aca` (tree `274eec56e3b4f3d254b4b29cf706dd27e5fee16b`) for EPIC #28905 P5 / #29700. The change adds the strict Official-only result-email projection, snapshots eligibility/source/brand into Run callbacks, and uses an atomic permanent claim plus the existing email outbox to deliver at most one bounded, escaped, branded result for each eligible successful Automation Run.

The authored base is `d24888e360664ac892d1be16788f5b75abd2a26a`. Current `main` is `5c46336786140483bda4208015e478fece4a6fec`; its three later commits touch no PR file, the read-only merge tree is clean (`d3f9f431e445c1c6fbbf942c2f2999fb76f9c69f`), and the canonical journal still ends at `1013_calm_darwin`.

### Findings

#### Critical (P0)

- None.

#### High Priority (P1)

- None. The prior exact-head findings are repaired: the accepted runtime has no `default(false)`, migration `1014_puzzling_skrulls` has no backfill/function/trigger compatibility bridge, the redundant schema-only contract test is removed, and the PR body declares `## Fallbacks` as none.

### Review criteria evaluation

| Source | Result | Evidence |
| --- | --- | --- |
| `REVIEW.md` | Pass | Strict payloads and persisted identities; atomic claim/outbox insertion; typed API/DB boundaries; complete feature regression coverage. |
| `docs/docs.md` | Pass | Applicable production, testing, fallback, deployment, ccstate, and reference-identity practices were selected and reviewed. |
| `docs/bad-smell.md` | Pass | No new `any`, suppression directives, dynamic imports, hard-coded deployment configuration, or accidental compatibility branches. |
| `docs/testing.md`, `docs/testing/patterns.md`, `docs/testing/anti-patterns.md` | Pass | DB-backed lifecycle matrix, deterministic clock cleanup, concurrent redrive, physical identity, and migration tests; no fake-timer/global-fetch/mock-heavy shortcut. |
| `docs/testing/api-testing.md`, `docs/testing/testing-external-behavior.md` | Pass | Install, reconfigure, run, completion, unsubscribe, suppression, and deletion use public route boundaries; test-only routes are limited to crash/interruption, exact outbox cleanup, and concurrent callback states that public APIs cannot construct. |
| `.claude/skills/ccstate/SKILL.md` | Pass | New command paths propagate `AbortSignal`, check cancellation around I/O, and introduce no detached signal lifecycle or computed-side mutation. |
| `docs/fallback.md` | Pass | No old-shape tolerance remains. Empty-output copy is required product behavior, not a compatibility fallback; the staff-only non-GA catalog has one strict runtime shape. |
| `docs/deployment-compatibility.md` | Pass | The migration is additive (new table and nullable columns) and changes the Official binding constraint only; the disabled/staff-only empty catalog prevents old-code Official writes during the deployment window. |
| `docs/externally-managed-references.md` | Pass | Source Automation ID, Workflow name, and public brand are immutable launch snapshots; callback retry never substitutes or depends on a live Automation, and the non-FK claim intentionally survives Run/Automation/outbox deletion. |

### Testing

- Coverage: Adequate. Official catalog sync is 12/12; Official install/admission/lifecycle is 16/16; result-email lifecycle is 7/7. The matrix covers explicit, scheduled, once, and webhook launches; enabled/disabled reconfiguration; uninstall; cancellation/failure; account unsubscribe; provider suppression; output escaping/bounds/empty output; session and agent-token brands; concurrent duplicate delivery; and pending/failed TTL cleanup with late redrive.
- Migration: snapshot `1014` points exactly to canonical `1013`; normalized schema delta is limited to the claim table, source pair, Official result-email column, and their indexes/checks. `test-migrate` and generator no-op evidence pass.
- Exact-head CI: attempt 2 of Turbo run `33091844411` is successful, including all API/App shards, `test-migrate`, `test-other`, lint, format, types, Knip, previews, CLI and Runner E2E. Security, Crates, Runner Image, and Code Quality also pass. Attempt 1's sole timeout was the untouched image-annotation test; its dedicated stabilization #29942 is now on `main`, and the same exact PR head passed on attempt 2.
- Conventions: Compliant. No full local Vitest suite or local dev server was used.

This exact head is cleared only for the normal protected merge queue. Any head change invalidates this clearance and requires a fresh controller review. Auto-merge was disabled at review time; no direct merge, bypass, or Production Release action is authorized by this review.

**Review by lancy — COMMENTED** [review]
Changes Requested

### Summary

Independent review of exact head `9f0f0fc5039d090e53b07123a03d6d0e6dde0d2b` (tree `a6a39cd702d27d7d83c489208fb312d1b25ed655`) against #29700 and EPIC #28905 P5. The rebase over #29938 preserves the strict Official-only projection, exact launch provenance and mounts, immutable callback source and public-brand snapshot, permanent source claim, bounded escaped renderer, and ordinary-path isolation. One acceptance-critical unsubscribe race remains, so this exact head is not cleared for the merge queue.

### Review Criteria

| Source | Result | Evidence |
| --- | --- | --- |
| `REVIEW.md` correctness and logic | Finding (P1) | A committed account unsubscribe can occur after the preference read and before the outbox transaction, yet the email is still enqueued. |
| `REVIEW.md` security and authorization | Pass | Run ownership, Official-only eligibility, exact source identity, and immutable callback payload remain fail-closed. |
| `REVIEW.md` types, DB, and compatibility | Pass | Strict typed payloads, additive 1016 schema, physical identities, generator no-op, and migration validation are aligned; no compatibility fallback is introduced. |
| `docs/bad-smell.md` | Pass | No new unsafe type escape, suppression directive, dynamic import, or hidden compatibility branch was found. |
| `docs/testing.md` and testing practice docs | Finding (P1) | Existing unsubscribe coverage proves only unsubscribe-before-callback; it does not exercise the production interleaving below. |
| `.claude/skills/ccstate/SKILL.md` | Pass | Callback command/signal propagation and transactional side effects follow the established ownership model. |
| `docs/fallback.md` | Pass | The PR declares no fallback and the exact diff contains no old-shape tolerance or backfill bridge. |
| `docs/deployment-compatibility.md` | Pass | The disabled, staff-only empty Official catalog keeps the additive migration and old/new API window safe. |

### Findings

#### Critical (P0)

- None.

#### High Priority (P1) - should fix before merge

- `turbo/apps/api/src/signals/services/internal-workflow-automation-result-email-callback.service.ts:127` checks `users.emailUnsubscribed` before the Clerk lookup and Run-output read, then inserts the permanent claim and outbox row in a later transaction at lines 143-192. A concurrent unsubscribe can therefore commit through `email-unsubscribe.service.ts:61-70` after line 127 returns `false` but before line 164 inserts the outbox row. The drain path in `email-common.service.ts:485-510` checks only `email_suppressions`, not `users.emailUnsubscribed`, so that row can be sent. Deterministic reproduction: pause a completing callback after its preference read, commit the account-unsubscribe POST, release the callback, then drain; the current code creates the claim/outbox and sends despite the unsubscribe having committed before enqueue. This violates #29700's required behavior and acceptance criterion that account unsubscribe prevents enqueue. Serialize the final preference decision with enqueue (for example, a transactionally locked final re-read coordinated with the unsubscribe update) and add a DB-backed interleaving regression that proves no claim or outbox row is created.

### Testing

- Exact-head CI is fully green (79 success, 17 intentional skips), including `test-migrate`, all API/App shards, lint, types, Knip, Security, Crates, Runner Image, and E2E. This does not cover the race above.
- The focused 7/7 result-email lifecycle suite covers unsubscribe that is already committed before callback delivery, suppression, retries, TTL cleanup, and concurrent redrive. Add the precise unsubscribe-between-read-and-insert interleaving; a timing-only test is insufficient.
- Any head change invalidates this review. Keep auto-merge and queue entry disabled until a fresh exact-head controller clearance. No direct merge, bypass, or Production Release action is authorized.

**Review by lancy — COMMENTED** [review]
LGTM

Independent whole-diff review is clear for exact head `21ddde572c31fd3e592a6bd10934a2f2d207dacf`, tree `f1cc1c6f870975d0c7dc44ef6aef89f6f1396de5`, against base `3941a9832964c22b647213509376be0fccb70683`.

### Findings

- P0: none.
- P1: none.
- The previously reported unsubscribe-after-read-before-enqueue race is closed. The callback transaction now materializes and locks the canonical `users(id)` row, re-reads `emailUnsubscribed` after acquiring that lock, and only then inserts the permanent source claim and outbox row atomically. Explicit unsubscribe and complaint handling serialize through the same row. The absent-row unsubscribe-first and enqueue-first interleavings are covered with deterministic PostgreSQL tests.

### Review Criteria

| Criterion | Result |
| --- | --- |
| Correctness, security, and type safety | Pass. Eligibility remains an immutable Official launch snapshot; the final preference lock closes the lost-unsubscribe window; claim and outbox insertion remain atomic and idempotent. |
| Bad-smell audit | Pass. No unsafe cast, suppression, dynamic import, compatibility fallback, or unrelated abstraction was introduced. |
| Testing quality | Pass. The race regression uses controlled database interleavings rather than timing sleeps or fake timers, and covers both serialization outcomes from an absent user row. |
| API external behavior | Pass. Public unsubscribe behavior remains exercised through the route; the test-only fixture is limited to the otherwise-unreachable transaction interleaving boundary. |
| Cancellation and shutdown propagation | Pass. Abort signals continue through callback work, and transactional cancellation rolls back claim/outbox writes. |
| Fallback declaration | Pass. `## Fallbacks` explicitly declares none; the Official binding remains strict with no default/backfill tolerance. |
| Deployment compatibility | Pass. Migration `1016_short_korvac` is additive for the rollout window and preserves ordinary nullable behavior. |
| Externally managed references | Pass. The immutable launch snapshot and permanent non-FK source claim preserve the authoritative external identity without live-state rereads. |

### Validation

- GitHub authoritative diff: 35 files; local tree names and blob SHAs match exactly.
- Exact-head Turbo run: https://github.com/vm0-ai/vm0/actions/runs/33101668006
- Exact-head required PR checks completed successfully; only intentional skips remain.
- Focused PostgreSQL lifecycle, catalog sync, schema/migration, copy isolation, outbox cleanup, and physical-identity evidence is consistent with the reviewed implementation.

This clearance applies only to exact head `21ddde572c31fd3e592a6bd10934a2f2d207dacf` and authorizes only the normal protected merge queue. Any head change invalidates this clearance. No direct merge, protection bypass, or Production Release action is authorized by this review.
